version: '3.6'
services:
  bind:
    image: eafxx/bind
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 10000:10000
    volumes:
      - 'bind:/data'
    environment:
      - WEBMIN_ENABLED=true
      - WEBMIN_INIT_SSL_ENABLED=false
      # Referers specifies a hostname from where the webmin dashboard is reachable, set it to * to initially access it.
      - WEBMIN_INIT_REFERERS=*
      - WEBMIN_INIT_REDIRECT_PORT=10000
      - ROOT_PASSWORD=sml12345
      - TZ=Europe/Zurich
volumes:
  bind: